import type { Project } from "../types";

/**
 * Sample project (an EV charging station firmware model) used as the browser
 * fallback so the UI is demonstrable without the Tauri file backend. Mirrors
 * the data in the Claude Design prototype, mapped onto the real model.
 */
export function seedProject(): Project {
  return {
    needs: [
      {
        kind: "need",
        id: "N-001",
        title: "Unattended charge completion",
        status: "approved",
        moscow: "must",
        source: "Customer interview · Acme Fleet Ops",
        tags: ["reliability", "driver-ux"],
        created: "2026-06-02",
        body: "Once a charging session is authorized it must run to completion — reaching the target state of charge or a deliberate driver stop — without requiring any further interaction from the driver or a site operator, including automatic recovery from transient faults.",
      },
      {
        kind: "need",
        id: "N-002",
        title: "Multi-standard connector support",
        status: "approved",
        moscow: "should",
        source: "Competitive analysis · Q1 2026",
        tags: ["compatibility", "hardware"],
        created: "2026-06-02",
        body: "The station should support CCS2 and CHAdeMO connectors concurrently so mixed fleets can charge at a single site without provisioning separate hardware.",
      },
      {
        kind: "need",
        id: "N-003",
        title: "Remote fleet monitoring",
        status: "draft",
        moscow: "should",
        source: "Operations workshop · Mar 2026",
        tags: ["operations", "telemetry"],
        created: "2026-06-05",
        body: "Site operators need real-time visibility of every station's availability, session progress, and fault state from a single central dashboard.",
      },
      {
        kind: "need",
        id: "N-004",
        title: "Off-peak cost optimization",
        status: "draft",
        moscow: "could",
        source: "Product strategy memo",
        tags: ["cost", "grid"],
        created: "2026-06-10",
        body: "Where tariff data is available, the system could shift non-urgent charging into lower-cost windows to reduce operating cost without missing the driver's departure deadline.",
      },
      {
        kind: "need",
        id: "N-005",
        title: "OCPP 2.0.1 compliance",
        status: "approved",
        moscow: "must",
        source: "Regulatory requirement",
        tags: ["compliance", "protocol"],
        created: "2026-06-02",
        body: "The station must implement the OCPP 2.0.1 protocol for interoperability with third-party charge-point management systems and to satisfy procurement requirements.",
      },
    ],
    useCases: [
      {
        kind: "use-case",
        id: "UC-001",
        title: "Start a charging session",
        status: "approved",
        moscow: "must",
        trace: ["N-001"],
        actors: ["Driver", "EVSE Controller", "Vehicle BMS"],
        preconditions: [
          "Station is in the Available state",
          "Connector is physically seated in the vehicle inlet",
        ],
        mainFlow: [
          "Driver plugs the connector into the vehicle.",
          "EVSE detects the connection and reads the vehicle's charging capabilities.",
          "Driver authorizes the session (RFID, app, or plug-and-charge).",
          "EVSE negotiates a charging profile with the vehicle BMS.",
          "EVSE begins energy delivery and shows live session status.",
          "Session continues until the target SoC is reached or the driver stops it.",
        ],
        altFlows: [
          { step: 3, text: "if authorization is declined, the EVSE returns to Available and shows an error to the driver." },
          { step: 5, text: "if the vehicle reports a fault during negotiation, the EVSE aborts the session and logs a diagnostic code." },
        ],
        stories: [
          {
            id: "US-001",
            as_a: "fleet driver",
            i_want: "to start charging by tapping my access card",
            so_that: "I don't need a separate app to begin a session.",
          },
          {
            id: "US-002",
            as_a: "driver in a hurry",
            i_want: "to see estimated time-to-full immediately",
            so_that: "I can decide whether to wait or come back later.",
          },
        ],
        created: "2026-06-12",
      },
      {
        kind: "use-case",
        id: "UC-002",
        title: "Authenticate via RFID card",
        status: "approved",
        moscow: "should",
        trace: ["N-001", "N-005"],
        actors: ["Driver", "EVSE Controller", "CPMS"],
        preconditions: ["Station has network connectivity to the CPMS"],
        mainFlow: [
          "Driver presents an RFID card to the reader.",
          "EVSE reads the card UID.",
          "EVSE requests authorization from the CPMS.",
          "CPMS validates the token and returns a decision.",
          "EVSE unlocks the session on approval.",
        ],
        altFlows: [
          { step: 3, text: "if the CPMS is unreachable, the EVSE falls back to a locally cached allow-list if one is configured." },
        ],
        stories: [
          {
            id: "US-003",
            as_a: "site operator",
            i_want: "every authentication attempt recorded",
            so_that: "I can audit who accessed the station and when.",
          },
        ],
        created: "2026-06-12",
      },
      {
        kind: "use-case",
        id: "UC-003",
        title: "Monitor station status remotely",
        status: "draft",
        moscow: "should",
        trace: ["N-003"],
        actors: ["Site Operator", "CPMS", "EVSE Controller"],
        preconditions: ["Station is commissioned and online"],
        mainFlow: [
          "EVSE publishes status and meter values on a fixed interval.",
          "CPMS aggregates telemetry across the site.",
          "Operator views station state on the dashboard.",
          "Operator drills into an individual session for detail.",
        ],
        altFlows: [
          { step: 1, text: "if the station loses connectivity, the CPMS marks it Unknown after a heartbeat timeout." },
        ],
        stories: [
          {
            id: "US-004",
            as_a: "site operator",
            i_want: "to be alerted the moment a station faults",
            so_that: "I can dispatch a technician before drivers are affected.",
          },
        ],
        created: "2026-06-18",
      },
      {
        kind: "use-case",
        id: "UC-004",
        title: "Schedule off-peak charging",
        status: "draft",
        moscow: "could",
        trace: ["N-004"],
        actors: ["Driver", "EVSE Controller", "Tariff Service"],
        preconditions: ["Driver has opted into smart scheduling", "A departure time is known"],
        mainFlow: [
          "Driver sets a departure time and minimum SoC.",
          "EVSE fetches the tariff forecast.",
          "EVSE computes the lowest-cost charging window.",
          "EVSE defers delivery until the optimal window, guaranteeing SoC by departure.",
        ],
        altFlows: [
          { step: 2, text: "if no tariff data is available, the EVSE charges immediately at the standard profile." },
        ],
        stories: [
          {
            id: "US-005",
            as_a: "cost-conscious driver",
            i_want: "my car charged by 7am at the lowest price",
            so_that: "I save money without having to think about it.",
          },
        ],
        created: "2026-06-20",
      },
    ],
    requirements: [
      {
        kind: "requirement",
        id: "R-001",
        title: "Begin delivery on authorization",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "event-driven",
        created: "2026-06-25",
        body: "WHEN a vehicle is connected and the session is authorized, the EVSE shall begin energy delivery within 5 seconds.",
      },
      {
        kind: "requirement",
        id: "R-002",
        title: "Active-session current sampling",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "state-driven",
        created: "2026-06-25",
        body: "WHILE a charging session is active, the EVSE shall sample output current at a rate of at least 10 Hz.",
      },
      {
        kind: "requirement",
        id: "R-003",
        title: "Overcurrent protection",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "unwanted-behavior",
        created: "2026-06-25",
        body: "IF the measured output current exceeds the connector's rated limit, THEN the EVSE shall interrupt energy delivery within 100 ms.",
      },
      {
        kind: "requirement",
        id: "R-004",
        title: "Authentication audit log",
        status: "approved",
        moscow: "should",
        trace: ["UC-002"],
        format: "EARS",
        ears: "ubiquitous",
        created: "2026-06-26",
        body: "The EVSE shall record every authentication attempt with its card UID, timestamp, and outcome.",
      },
      {
        kind: "requirement",
        id: "R-005",
        title: "Tariff-aware scheduling",
        status: "draft",
        moscow: "could",
        trace: ["UC-004"],
        format: "EARS",
        ears: "optional",
        created: "2026-06-28",
        body: "WHERE tariff forecast data is available, the EVSE shall schedule charging to complete within the lowest-cost window before the driver's departure time.",
      },
      {
        kind: "requirement",
        id: "R-006",
        title: "Heartbeat timeout handling",
        status: "draft",
        moscow: "should",
        trace: ["UC-003"],
        format: "EARS",
        ears: "complex",
        created: "2026-06-28",
        body: "WHEN a heartbeat is not received for 3 consecutive intervals WHILE the station is commissioned, the EVSE shall transition the station to the Unknown state and emit a StatusNotification.",
      },
      {
        kind: "requirement",
        id: "R-007",
        title: "Emergency stop response",
        status: "draft",
        moscow: "must",
        trace: [],
        format: "EARS",
        ears: "event-driven",
        created: "2026-06-30",
        body: "WHEN the emergency-stop button is pressed, the EVSE shall de-energize all connectors within 50 ms.",
      },
    ],
  };
}
