import type { Project } from "../types";

/**
 * Sample project (an EV charging station firmware model) used as the browser
 * fallback so the UI is demonstrable without the Tauri file backend. Mirrors
 * the data in the Claude Design prototype, mapped onto the real model.
 */
export function seedProject(): Project {
  return {
    stakeholders: [
      {
        kind: "stakeholder",
        id: "SH-001",
        title: "Fleet Operator",
        type: "primary",
        created: "2026-06-01",
        body: "Runs a fleet of electric vehicles that depend on the station being available and reliable overnight. Cares most about sessions completing unattended.",
      },
      {
        kind: "stakeholder",
        id: "SH-002",
        title: "Site Operator",
        type: "primary",
        created: "2026-06-01",
        body: "Owns and maintains the physical charging site. Needs to monitor station health and be alerted to faults before drivers are affected.",
      },
      {
        kind: "stakeholder",
        id: "SH-003",
        title: "Product Manager",
        type: "primary",
        created: "2026-06-01",
        body: "Owns the product roadmap and competitive positioning. Balances hardware compatibility and cost-optimisation features against delivery timelines.",
      },
      {
        kind: "stakeholder",
        id: "SH-004",
        title: "Compliance Officer",
        type: "secondary",
        created: "2026-06-01",
        body: "Ensures the station meets regulatory and procurement requirements such as the OCPP protocol. Not a day-to-day user but gates release.",
      },
    ],
    needs: [
      {
        kind: "need",
        id: "N-001",
        title: "Unattended charge completion",
        status: "approved",
        moscow: "must",
        stakeholder: "SH-001",
        source: "Customer interview · Acme Fleet Ops",
        tags: ["reliability", "driver-ux"],
        created: "2026-06-02",
        body: "Once a charging session is authorized it must run to completion — reaching the target state of charge or a deliberate driver stop — without requiring any further interaction from the driver or a site operator, including automatic recovery from transient faults.",
      },
      {
        kind: "need",
        id: "N-002",
        title: "Multi-standard connector support",
        status: "approved",
        moscow: "should",
        stakeholder: "SH-003",
        source: "Competitive analysis · Q1 2026",
        tags: ["compatibility", "hardware"],
        created: "2026-06-02",
        body: "The station should support CCS2 and CHAdeMO connectors concurrently so mixed fleets can charge at a single site without provisioning separate hardware.",
      },
      {
        kind: "need",
        id: "N-003",
        title: "Remote fleet monitoring",
        status: "draft",
        moscow: "should",
        stakeholder: "SH-002",
        source: "Operations workshop · Mar 2026",
        tags: ["operations", "telemetry"],
        created: "2026-06-05",
        body: "Site operators need real-time visibility of every station's availability, session progress, and fault state from a single central dashboard.",
      },
      {
        kind: "need",
        id: "N-004",
        title: "Off-peak cost optimization",
        status: "draft",
        moscow: "could",
        stakeholder: "SH-003",
        source: "Product strategy memo",
        tags: ["cost", "grid"],
        created: "2026-06-10",
        // Example of the inferred marker: a speculative need to be confirmed.
        inferred: true,
        body: "Where tariff data is available, the system could shift non-urgent charging into lower-cost windows to reduce operating cost without missing the driver's departure deadline.",
      },
      {
        kind: "need",
        id: "N-005",
        title: "OCPP 2.0.1 compliance",
        status: "approved",
        moscow: "must",
        stakeholder: "SH-004",
        source: "Regulatory requirement",
        tags: ["compliance", "protocol"],
        created: "2026-06-02",
        body: "The station must implement the OCPP 2.0.1 protocol for interoperability with third-party charge-point management systems and to satisfy procurement requirements.",
      },
    ],
    useCases: [
      {
        kind: "use-case",
        id: "UC-001",
        title: "Start a charging session",
        status: "approved",
        moscow: "must",
        trace: ["N-001"],
        actors: ["Driver", "EVSE Controller", "Vehicle BMS"],
        preconditions: [
          "Station is in the Available state",
          "Connector is physically seated in the vehicle inlet",
        ],
        flow: "FL-001",
        stories: [
          {
            id: "US-001",
            as_a: "fleet driver",
            i_want: "to start charging by tapping my access card",
            so_that: "I don't need a separate app to begin a session.",
          },
          {
            id: "US-002",
            as_a: "driver in a hurry",
            i_want: "to see estimated time-to-full immediately",
            so_that: "I can decide whether to wait or come back later.",
          },
        ],
        created: "2026-06-12",
      },
      {
        kind: "use-case",
        id: "UC-002",
        title: "Authenticate via RFID card",
        status: "approved",
        moscow: "should",
        trace: ["N-001", "N-005"],
        actors: ["Driver", "EVSE Controller", "CPMS"],
        preconditions: ["Station has network connectivity to the CPMS"],
        flow: "FL-002",
        stories: [
          {
            id: "US-003",
            as_a: "site operator",
            i_want: "every authentication attempt recorded",
            so_that: "I can audit who accessed the station and when.",
          },
        ],
        created: "2026-06-12",
      },
      {
        kind: "use-case",
        id: "UC-003",
        title: "Monitor station status remotely",
        status: "draft",
        moscow: "should",
        trace: ["N-003"],
        actors: ["Site Operator", "CPMS", "EVSE Controller"],
        preconditions: ["Station is commissioned and online"],
        flow: "FL-003",
        stories: [
          {
            id: "US-004",
            as_a: "site operator",
            i_want: "to be alerted the moment a station faults",
            so_that: "I can dispatch a technician before drivers are affected.",
          },
        ],
        created: "2026-06-18",
      },
      {
        kind: "use-case",
        id: "UC-004",
        title: "Schedule off-peak charging",
        status: "draft",
        moscow: "could",
        trace: ["N-004"],
        actors: ["Driver", "EVSE Controller", "Tariff Service"],
        preconditions: ["Driver has opted into smart scheduling", "A departure time is known"],
        flow: "FL-004",
        stories: [
          {
            id: "US-005",
            as_a: "cost-conscious driver",
            i_want: "my car charged by 7am at the lowest price",
            so_that: "I save money without having to think about it.",
          },
        ],
        created: "2026-06-20",
      },
    ],
    requirements: [
      {
        kind: "requirement",
        id: "R-001",
        title: "Begin delivery on authorization",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "event-driven",
        condition: "a vehicle is connected and the session is authorized",
        subject: "EVSE",
        action: "begin energy delivery",
        object: "",
        constraint: "within 5 seconds",
        created: "2026-06-25",
      },
      {
        kind: "requirement",
        id: "R-002",
        title: "Active-session current sampling",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "state-driven",
        condition: "a charging session is active",
        subject: "EVSE",
        action: "sample output current",
        object: "",
        constraint: "at a rate of at least 10 Hz",
        created: "2026-06-25",
      },
      {
        kind: "requirement",
        id: "R-003",
        title: "Overcurrent protection",
        status: "approved",
        moscow: "must",
        trace: ["UC-001"],
        format: "EARS",
        ears: "unwanted-behavior",
        condition: "the measured output current exceeds the connector's rated limit",
        subject: "EVSE",
        action: "interrupt energy delivery",
        object: "",
        constraint: "within 100 ms",
        created: "2026-06-25",
      },
      {
        kind: "requirement",
        id: "R-004",
        title: "Authentication audit log",
        status: "approved",
        moscow: "should",
        trace: ["UC-002"],
        format: "EARS",
        ears: "ubiquitous",
        condition: "",
        subject: "EVSE",
        action: "record every authentication attempt",
        object: "with its card UID, timestamp, and outcome",
        constraint: "",
        created: "2026-06-26",
      },
      {
        kind: "requirement",
        id: "R-005",
        title: "Tariff-aware scheduling",
        status: "draft",
        moscow: "could",
        trace: ["UC-004"],
        format: "EARS",
        ears: "optional",
        condition: "tariff forecast data is available",
        subject: "EVSE",
        action: "schedule charging",
        object: "",
        constraint: "to complete within the lowest-cost window before the driver's departure time",
        created: "2026-06-28",
      },
      {
        kind: "requirement",
        id: "R-006",
        title: "Heartbeat timeout handling",
        status: "draft",
        moscow: "should",
        trace: ["UC-003"],
        format: "EARS",
        ears: "complex",
        condition: "a heartbeat is not received for 3 consecutive intervals while the station is commissioned",
        subject: "EVSE",
        action: "transition the station to the Unknown state and emit a StatusNotification",
        object: "",
        constraint: "",
        created: "2026-06-28",
      },
      {
        kind: "requirement",
        id: "R-007",
        title: "Emergency stop response",
        status: "draft",
        moscow: "must",
        trace: [],
        format: "EARS",
        ears: "event-driven",
        condition: "the emergency-stop button is pressed",
        subject: "EVSE",
        action: "de-energize all connectors",
        object: "",
        constraint: "within 50 ms",
        created: "2026-06-30",
      },
    ],
    components: [
      {
        kind: "component",
        id: "C-001",
        title: "Driver Interface",
        parent: "C-002",
        description:
          "The card reader, display and buttons the driver interacts with at the station.",
        created: "2026-07-01",
        activities: [
          { id: "ACT-001", label: "Tap access card" },
          { id: "ACT-002", label: "Show time-to-full estimate" },
        ],
        variables: [],
        decisions: [],
      },
      {
        kind: "component",
        id: "C-002",
        title: "EVSE Controller",
        parent: "",
        description:
          "The station's firmware controller: orchestrates authorization, energy delivery and safety monitoring.",
        created: "2026-07-01",
        activities: [
          { id: "ACT-003", label: "Request authorization" },
          {
            id: "ACT-004",
            label: "Begin energy delivery",
            pre: "evseController.state == idle",
            effects: ["evseController.state := delivering"],
          },
          { id: "ACT-005", label: "Sample output current" },
          {
            id: "ACT-006",
            label: "Reject the session",
            effects: ["evseController.state := fault"],
          },
        ],
        variables: [
          {
            id: "VAR-001",
            name: "state",
            type: { kind: "enum", values: ["idle", "delivering", "fault"] },
            initial: "idle",
          },
        ],
        decisions: ["D-001"],
      },
      {
        kind: "component",
        id: "C-003",
        title: "Charge Point Management System",
        parent: "",
        description:
          "The back-office CPMS that authenticates cards and keeps the audit trail.",
        created: "2026-07-01",
        activities: [
          { id: "ACT-007", label: "Validate the card" },
          { id: "ACT-008", label: "Record an audit entry" },
        ],
        variables: [
          {
            id: "VAR-002",
            name: "cardRecognised",
            type: { kind: "bool" },
            initial: "true",
          },
        ],
        decisions: ["D-002"],
      },
      {
        kind: "component",
        id: "C-004",
        title: "Vehicle BMS",
        parent: "",
        description: "The vehicle's battery management system, negotiated with over the connector.",
        created: "2026-07-01",
        activities: [{ id: "ACT-009", label: "Report target state of charge" }],
        variables: [],
        decisions: [],
      },
    ],
    flows: [
      {
        kind: "flow",
        id: "FL-001",
        title: "Start a charging session",
        created: "2026-07-02",
        // Driver → EVSE → CPMS → EVSE → BMS → EVSE
        main: ["ACT-001", "ACT-003", "ACT-007", "ACT-004", "ACT-009", "ACT-005"],
        alternates: [
          {
            id: "AP-1",
            condition: "the card is not recognised",
            guard: "chargePointManagementSystem.cardRecognised == false",
            after: 2, // after "Validate the card"
            rejoin: -1, // terminates the flow
            steps: ["ACT-006"], // EVSE rejects the session
          },
        ],
      },
      {
        kind: "flow",
        id: "FL-002",
        title: "Authenticate via RFID card",
        created: "2026-07-02",
        // Driver → EVSE → CPMS → CPMS
        main: ["ACT-001", "ACT-003", "ACT-007", "ACT-008"],
        alternates: [],
      },
    ],
    decisions: [
      {
        kind: "decision",
        id: "D-001",
        title: "Hardware overcurrent interrupt",
        status: "accepted",
        trace: ["UC-001"],
        context: "station power stage",
        concern: "an overcurrent fault can damage the connector and vehicle faster than firmware can react",
        decision: "interrupt energy delivery in hardware within 100 ms of an overcurrent",
        alternatives: "detecting overcurrent by polling in the firmware control loop",
        criterion: "driver and equipment safety independent of software timing",
        downside: "an occasional false trip on a transient current spike",
        created: "2026-07-03",
      },
      {
        kind: "decision",
        id: "D-002",
        title: "Validate cards at the CPMS",
        status: "accepted",
        trace: ["UC-002"],
        context: "card authentication path",
        concern: "a station could be tricked by a cloned card if it decides locally",
        decision: "validate every card against the central CPMS before authorizing",
        alternatives: "caching an allow-list of card UIDs on the station for offline use",
        criterion: "central revocation and a single authoritative audit trail",
        downside: "a hard dependency on network connectivity to start a session",
        created: "2026-07-03",
      },
    ],
    tests: [
      {
        kind: "test",
        id: "T-001",
        title: "Delivery starts within 5s of authorization",
        trace: ["R-001"],
        file: "firmware/test/delivery_start_test.c",
        result: "pass",
        created: "2026-07-04",
        body: "Authorizes a session on a bench rig and asserts energy delivery begins within the 5-second budget.",
      },
      {
        kind: "test",
        id: "T-002",
        title: "Overcurrent trips within 100ms",
        trace: ["R-003"],
        file: "firmware/test/overcurrent_test.c",
        result: "fail",
        created: "2026-07-04",
        body: "Injects an overcurrent above the connector's rated limit and measures the interrupt latency. Currently failing: trip observed at ~140 ms.",
      },
    ],
    glossary: [
      {
        kind: "glossary",
        id: "G-001",
        title: "EVSE",
        aliases: ["Electric Vehicle Supply Equipment", "charge point"],
        created: "2026-07-03",
        definition:
          "The charging station hardware and firmware that delivers energy to a vehicle and enforces the safety envelope during a session.",
      },
      {
        kind: "glossary",
        id: "G-002",
        title: "CPMS",
        aliases: ["Charge Point Management System", "back office"],
        created: "2026-07-03",
        definition:
          "The central back-office system a station talks to (over OCPP) for card authorization, telemetry, and remote control.",
      },
      {
        kind: "glossary",
        id: "G-003",
        title: "State of charge",
        aliases: ["SoC"],
        created: "2026-07-03",
        definition:
          "The battery's current charge level as a percentage of its capacity. Reaching the target state of charge is one way a session completes.",
      },
    ],
  };
}
